//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDatabaseTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
        }

        public OrderDetail(int modelID, int orderID, int accessoryID)
        {
            this.ModelID = modelID;
            this.OrderID = orderID;
            this.AccessoryID = accessoryID;
        }

        public int ModelID { get; set; }
        public int OrderID { get; set; }
        public int AccessoryID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Model Model { get; set; }
        public virtual Order Order { get; set; }
    }
}
